// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NXT25_AST4_SWD5_S2_InGym.Data;

#nullable disable

namespace NXT25_AST4_SWD5_S2InGym.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260710132959_MakeCoachOptional")]
    partial class MakeCoachOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Attendance", b =>
                {
                    b.Property<int>("AttendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendID"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("AttendID");

                    b.HasIndex("MemberID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Coach", b =>
                {
                    b.Property<int>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachID"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CoachID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.DietaryPlan", b =>
                {
                    b.Property<int>("DietID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietID"));

                    b.Property<int>("CalorieTarget")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProteinTarget")
                        .HasColumnType("int");

                    b.HasKey("DietID");

                    b.ToTable("DietaryPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Gym", b =>
                {
                    b.Property<int>("GymID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymID"));

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GymID");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymCoach", b =>
                {
                    b.Property<int>("GymID")
                        .HasColumnType("int");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.HasKey("GymID", "CoachID");

                    b.HasIndex("CoachID");

                    b.ToTable("GymCoaches");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymLocation", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<int>("GymID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.HasIndex("GymID");

                    b.ToTable("GymLocations");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymManager", b =>
                {
                    b.Property<int>("ManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerID"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ManagerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("GymManagers");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymMember", b =>
                {
                    b.Property<int>("GymID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("GymID", "MemberID");

                    b.HasIndex("MemberID");

                    b.ToTable("GymMembers");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymSub", b =>
                {
                    b.Property<int>("GymSubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymSubID"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GymSubID");

                    b.ToTable("GymSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.HealthMetricLog", b =>
                {
                    b.Property<int>("MetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricID"));

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("MetricID");

                    b.ToTable("HealthMetricLogs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChronicDiseases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhysRestrictions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("MemberID");

                    b.HasIndex("CoachID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberDietaryPlan", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("DietID")
                        .HasColumnType("int");

                    b.Property<int>("DietaryPlanDietID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "DietID");

                    b.HasIndex("DietaryPlanDietID");

                    b.ToTable("MemberDietaryPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberGymSub", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("GymSubID")
                        .HasColumnType("int");

                    b.Property<int>("GymID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "GymSubID");

                    b.HasIndex("GymID");

                    b.HasIndex("GymSubID");

                    b.ToTable("MemberGymSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberHealthMetric", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("MetricID")
                        .HasColumnType("int");

                    b.Property<int>("HealthMetricLogMetricID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "MetricID");

                    b.HasIndex("HealthMetricLogMetricID");

                    b.ToTable("MemberHealthMetrics");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberPrivateSub", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PrivateSubID")
                        .HasColumnType("int");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "PrivateSubID");

                    b.HasIndex("CoachID");

                    b.HasIndex("PrivateSubID");

                    b.ToTable("MemberPrivateSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberWorkoutPlan", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanPlanID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "PlanID");

                    b.HasIndex("WorkoutPlanPlanID");

                    b.ToTable("MemberWorkoutPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.PrivateSub", b =>
                {
                    b.Property<int>("PrivateSubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrivateSubID"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.HasKey("PrivateSubID");

                    b.ToTable("PrivateSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.UserPhone", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID", "Phone");

                    b.ToTable("UserPhones");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanID");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseID")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanPlanID")
                        .HasColumnType("int");

                    b.HasKey("PlanID", "ExerciseID");

                    b.HasIndex("ExerciseID");

                    b.HasIndex("WorkoutPlanPlanID");

                    b.ToTable("WorkoutPlanExercises");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Attendance", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Coach", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("NXT25_AST4_SWD5_S2_InGym.Models.Coach", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymCoach", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Coach", "Coach")
                        .WithMany("GymCoaches")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Gym", "Gym")
                        .WithMany("GymCoaches")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymLocation", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Gym", "Gym")
                        .WithMany("GymLocations")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymManager", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.User", "User")
                        .WithOne("GymManager")
                        .HasForeignKey("NXT25_AST4_SWD5_S2_InGym.Models.GymManager", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymMember", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Gym", "Gym")
                        .WithMany("GymMembers")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("GymMembers")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Member", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Coach", "Coach")
                        .WithMany("Members")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("NXT25_AST4_SWD5_S2_InGym.Models.Member", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberDietaryPlan", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.DietaryPlan", "DietaryPlan")
                        .WithMany("MemberDietaryPlans")
                        .HasForeignKey("DietaryPlanDietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("MemberDietaryPlans")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryPlan");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberGymSub", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Gym", "Gym")
                        .WithMany("MemberGymSubs")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.GymSub", "GymSub")
                        .WithMany("MemberGymSubs")
                        .HasForeignKey("GymSubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("MemberGymSubs")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymSub");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberHealthMetric", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.HealthMetricLog", "HealthMetricLog")
                        .WithMany("MemberHealthMetrics")
                        .HasForeignKey("HealthMetricLogMetricID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("MemberHealthMetrics")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthMetricLog");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberPrivateSub", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Coach", "Coach")
                        .WithMany("MemberPrivateSubs")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("MemberPrivateSubs")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.PrivateSub", "PrivateSub")
                        .WithMany("MemberPrivateSubs")
                        .HasForeignKey("PrivateSubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");

                    b.Navigation("PrivateSub");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.MemberWorkoutPlan", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Member", "Member")
                        .WithMany("MemberWorkoutPlans")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("MemberWorkoutPlans")
                        .HasForeignKey("WorkoutPlanPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.UserPhone", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.User", "User")
                        .WithMany("UserPhones")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.Exercise", "Exercise")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanExercises")
                        .HasForeignKey("WorkoutPlanPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Coach", b =>
                {
                    b.Navigation("GymCoaches");

                    b.Navigation("MemberPrivateSubs");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.DietaryPlan", b =>
                {
                    b.Navigation("MemberDietaryPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutPlanExercises");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Gym", b =>
                {
                    b.Navigation("GymCoaches");

                    b.Navigation("GymLocations");

                    b.Navigation("GymMembers");

                    b.Navigation("MemberGymSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.GymSub", b =>
                {
                    b.Navigation("MemberGymSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.HealthMetricLog", b =>
                {
                    b.Navigation("MemberHealthMetrics");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("GymMembers");

                    b.Navigation("MemberDietaryPlans");

                    b.Navigation("MemberGymSubs");

                    b.Navigation("MemberHealthMetrics");

                    b.Navigation("MemberPrivateSubs");

                    b.Navigation("MemberWorkoutPlans");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.PrivateSub", b =>
                {
                    b.Navigation("MemberPrivateSubs");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.User", b =>
                {
                    b.Navigation("Coach");

                    b.Navigation("GymManager");

                    b.Navigation("Member");

                    b.Navigation("UserPhones");
                });

            modelBuilder.Entity("NXT25_AST4_SWD5_S2_InGym.Models.WorkoutPlan", b =>
                {
                    b.Navigation("MemberWorkoutPlans");

                    b.Navigation("WorkoutPlanExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
